# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brief_name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('website_url', models.URLField(null=True)),
                ('classification', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_and_time', models.DateTimeField()),
                ('brief_name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('website_url', models.URLField(null=True)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('ticket_url', models.URLField(null=True)),
                ('show_length', models.DurationField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brief_name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('website_url', models.URLField(null=True)),
                ('street_address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('zip_code', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Venue'),
        ),
    ]
