# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_venue_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        # Postgres won't allow this recasting, so remove it and re-add it
        #migrations.AlterField(
        #    model_name='event',
        #    name='show_length',
        #    field=models.IntegerField(null=True),
        #),
        migrations.RemoveField(
            model_name='event',
            name='show_length',
        ),
        migrations.AddField(
            model_name='event',
            name='show_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
