# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_auto_20170210_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
