# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0004_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(null=True, upload_to='company_images/'),
        ),
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.ImageField(null=True, upload_to='venue_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='event_images/'),
        ),
    ]
